// fe_vue/src/components/navbar/NavMenuDesktop.vue
<script setup lang="ts">
import userStore from '@/util/userStore';
import { computed } from 'vue';

const isAdmin = computed(() => userStore.state.user?.role === 'admin');
const isMember = computed(() => userStore.state.user?.role === 'member');
</script>

<template>
  <div class="NAV_MEN_DESKTOP flex space-x-4">
    <RouterLink
      to="/"
      class="text-white hover:text-gray-300"
      >Home</RouterLink
    >
    <RouterLink
      to="/lost-items"
      class="text-white hover:text-gray-300"
      >Lost Items</RouterLink
    >
    <RouterLink
      to="/found-items"
      class="text-white hover:text-gray-300"
      >Found Items</RouterLink
    >
    <template v-if="isAdmin">
      <RouterLink
        to="/admin"
        class="text-white hover:text-gray-300"
        >Admin</RouterLink
      >
    </template>
  </div>
</template>

// frontend/src/app/components/navbar/NavMenuDesktop.tsx
import Link from "next/link";

const NavMenuDesktop = ({
  isAdmin,
  isMember,
}: {
  isAdmin: boolean;
  isMember: boolean;
}) => {
  return (
    <div className="flex space-x-4">
      <Link href="/" className="text-white hover:text-gray-300">
        Home
      </Link>
      {(isMember || isAdmin) && (
        <Link href="/lost" className="text-white hover:text-gray-300">
          Lost Items
        </Link>
      )}
      {(isMember || isAdmin) && (
        <Link href="/found" className="text-white hover:text-gray-300">
          Found Items
        </Link>
      )}
      {isAdmin && (
        <Link href="/admin" className="text-white hover:text-gray-300">
          Admin Panel
        </Link>
      )}
    </div>
  );
};

export default NavMenuDesktop;
