// frontend/src/app/(auth)/login/page.tsx
'use client';
import React, { useState } from 'react';
import axios from 'axios';
import { useAuth } from '@/src/contexts/AuthContext';
import { useRouter } from 'next/navigation';

const LoginPage = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [processingLoginRequest, setProcessingLoginRequest] = useState(false); // This monitors API request
  const [redirecting, setRedirecting] = useState(false); // Separates successful API request and router push

  const { refreshProfile, loading } = useAuth();
  const router = useRouter(); 

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setProcessingLoginRequest(true);
    try {
      await axios.post(
        'http://localhost:8000/api/v1/auth/login/',
        { email, password },
        { withCredentials: true }
      );
      await refreshProfile();
      setRedirecting(true); 
      router.push('/dashboard');
    } catch (error) {
      console.error('Login error:', error);
      alert('Login failed. Check your credentials.');
    } finally {
      setProcessingLoginRequest(false);
    }
  };

  return (
    <div className='min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 px-4'>
      <div className='w-full max-w-md bg-white dark:bg-gray-800 shadow-md rounded-lg overflow-hidden'>
        <div className='px-6 py-4 border-b border-gray-200 dark:border-gray-700'>
          <h2 className='text-2xl font-bold text-white'>Login</h2>
          <p className='text-sm text-gray-400'>
            Enter your credentials to access the lost and found system
          </p>
        </div>
        <form onSubmit={handleSubmit} className='px-6 py-6 space-y-4'>
          <div className='space-y-2'>
            <label htmlFor='email' className='block text-sm font-medium text-gray-700 dark:text-gray-300'>
              Email
            </label>
            <input
              type='email'
              id='email'
              className='w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500'
              placeholder='email@example.com'
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
          </div>
          <div className='space-y-2'>
            <label htmlFor='password' className='block text-sm font-medium text-gray-700 dark:text-gray-300'>
              Password
            </label>
            <input
              type='password'
              id='password'
              className='w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500'
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </div>
          <button
            type='submit'
            disabled={processingLoginRequest}
            className='w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-md transition disabled:opacity-60 cursor-pointer'
          >
            {processingLoginRequest ? 'Logging in...' : 'Sign in'}
          </button>
        </form>

        <div className='px-6 pb-6 pt-2 border-t border-gray-200 dark:border-gray-700 text-sm text-gray-600 dark:text-gray-400'>
          <p className='text-center'>Demo Accounts:</p>
          <div className='mt-2 space-y-2 text-xs'>
            <div className='bg-gray-100 dark:bg-gray-700 p-2 rounded'>
              <strong>Admin:</strong> webdevelopmenthamilton@gmail.com / test123
            </div>
            <div className='bg-gray-100 dark:bg-gray-700 p-2 rounded'>
              <strong>Member:</strong> bob@hhsc.ca / testbob123
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LoginPage;

// fe_vue/src/views/Login.vue
<script setup lang="ts">
import { ref } from 'vue';
import userStore from '@/util/userStore';
import router from '@/router';

const email = ref('');
const password = ref('');

const onSubmit = async () => {
  try {
    await userStore.login(email.value, password.value);
    router.push('/');
  } catch (error) {
    console.error(error);
  }

  email.value = '';
  password.value = '';
};
</script>

<template>
  <div className="max-w-md mx-auto mt-8 p-6 bg-white rounded-lg shadow-md">
    <form
      id="form"
      @submit.prevent="onSubmit"
    >
      <div class="EMAIL_LABEL_AND_INPUT mb-4">
        <label
          for="email"
          class="block text-gray-700 font-bold mb-2"
          block
          text-gray-700
          font-bold
          mb-2
          >Email</label
        >
        <input
          v-model="email"
          type="email"
          id="email"
          name="email"
          class="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring focus:border-blue-500"
        />
      </div>
      <div class="PASSWORD_LABEL_AND_INPUT mb-4">
        <label
          for="password"
          class="block text-gray-700 font-bold mb-2"
          block
          text-gray-700
          font-bold
          mb-2
          >Password</label
        >
        <input
          v-model="password"
          type="password"
          id="password"
          name="password"
          class="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring focus:border-blue-500"
        />
      </div>
      <div class="LOGIN_BUTTON">
        <button
          type="submit"
          class="w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
        >
          Login
        </button>
      </div>
    </form>
  </div>
</template>
